# Generated by Django 4.2.11 on 2024-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="country_field",
            new_name="country",
        ),
    ]
