# Generated by Django 4.2.11 on 2024-11-07 15:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_country_field_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.TextField(
                choices=[
                    ("mason", "Mason"),
                    ("carpenter", "Carpenter"),
                    ("plummer", "Plummer"),
                    ("roofer", "Roofer"),
                    ("painter", "Painter"),
                    ("electrician", "Electrician"),
                    ("hvac", "HVAC"),
                    ("tennat", "Tennat"),
                ],
                default="tennat",
                verbose_name="Occupation",
            ),
        ),
    ]
