# Generated by Django 4.2.11 on 2024-11-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_avatar_alter_profile_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.TextField(
                choices=[
                    ("mason", "Mason"),
                    ("carpenter", "Carpenter"),
                    ("plummer", "Plummer"),
                    ("roofer", "Roofer"),
                    ("painter", "Painter"),
                    ("electrician", "Electrician"),
                    ("hvac", "HVAC"),
                    ("tenant", "Tenant"),
                ],
                default="tenant",
                verbose_name="Occupation",
            ),
        ),
    ]
